[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino
board_build.flash_size = 4MB
board_build.spiffs_size = 1MB
upload_speed = 115200
monitor_speed = 115200
build_flags =
    -D USE_PROGMEM_WEB_FILES
    -D SERIAL_BAUD=115200
    -D USE_DISPLAY=false
    -D NO_DISPLAY_MODULE
    -I lib
