name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: luid09/esp32-build:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      
      - name: Build firmware
        run: |
          pio run -e nodemcuv2
        working-directory: /workspace
        env:
          HOME: /root
          
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: firmware
          path: .pio/build/nodemcuv2/firmware.bin
